/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author jdelgado
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelTitulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        label = new javax.swing.JLabel();
        txtDist = new javax.swing.JTextField();
        label1 = new javax.swing.JLabel();
        txtPT = new javax.swing.JTextField();
        label2 = new javax.swing.JLabel();
        txtSR = new javax.swing.JTextField();
        label3 = new javax.swing.JLabel();
        txtAF = new javax.swing.JTextField();
        label4 = new javax.swing.JLabel();
        label5 = new javax.swing.JLabel();
        txtPPS = new javax.swing.JTextField();
        label6 = new javax.swing.JLabel();
        txtPC = new javax.swing.JTextField();
        label7 = new javax.swing.JLabel();
        jSpinnerQtdConectores = new javax.swing.JSpinner();
        jSpinnerQtdPS = new javax.swing.JSpinner();
        ButtonCalcular = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelTitulo.setFont(new java.awt.Font("Segoe UI", 3, 30)); // NOI18N
        LabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTitulo.setText("Calculador de Passive Optical Networks");
        getContentPane().add(LabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 20, 660, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label.setText("Distância");
        label.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 240, -1));

        txtDist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDistActionPerformed(evt);
            }
        });
        jPanel1.add(txtDist, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 240, -1));

        label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label1.setText("Potência de Transmissão");
        label1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 240, -1));

        txtPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPTActionPerformed(evt);
            }
        });
        jPanel1.add(txtPT, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 240, -1));

        label2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label2.setText("Sensibilidade de Recepção");
        label2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 240, -1));

        txtSR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSRActionPerformed(evt);
            }
        });
        jPanel1.add(txtSR, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 240, -1));

        label3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label3.setText("Atenuação da Fibra");
        label3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 240, -1));

        txtAF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAFActionPerformed(evt);
            }
        });
        jPanel1.add(txtAF, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 240, -1));

        label4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label4.setText("Qtd de Power Splitters");
        label4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 240, -1));

        label5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label5.setText("Qtd de Conectores");
        label5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 240, -1));

        txtPPS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPPSActionPerformed(evt);
            }
        });
        jPanel1.add(txtPPS, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 240, -1));

        label6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label6.setText("Perdas dos Power Splitters");
        label6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 240, -1));

        txtPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPCActionPerformed(evt);
            }
        });
        jPanel1.add(txtPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 240, -1));

        label7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label7.setText("Perdas dos Conectores");
        label7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 240, -1));
        jPanel1.add(jSpinnerQtdConectores, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 240, -1));
        jPanel1.add(jSpinnerQtdPS, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 240, -1));

        ButtonCalcular.setText("Calcular");
        ButtonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCalcularActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, 140, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 590, 440));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Resultado"));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 590, 170));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDistActionPerformed

    private void txtPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPTActionPerformed

    private void txtSRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSRActionPerformed

    private void txtAFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAFActionPerformed

    private void txtPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPCActionPerformed

    private void txtPPSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPPSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPPSActionPerformed

    private void ButtonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCalcularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCalcular;
    private javax.swing.JLabel LabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner jSpinnerQtdConectores;
    private javax.swing.JSpinner jSpinnerQtdPS;
    private javax.swing.JLabel label;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label6;
    private javax.swing.JLabel label7;
    private javax.swing.JTextField txtAF;
    private javax.swing.JTextField txtDist;
    private javax.swing.JTextField txtPC;
    private javax.swing.JTextField txtPPS;
    private javax.swing.JTextField txtPT;
    private javax.swing.JTextField txtSR;
    // End of variables declaration//GEN-END:variables
}
